### ISSUE TITLE
Tween canceled but still true when check isTweening

### ISSUE THREAD

**Issue by benzsuankularb** [dentedpixel/LeanTween#101]
Hello,
Is it a bug or by designed?

    if (LeanTween.isTweening (myTween.id)) {
       myTween.setOnComplete (doSome);
       LeanTween.cancel (myTween.id, true);
    }
    
    ...
    
    void doSome () {
       if (LeanTween.isTweening (myTween.id))
          Debug.Log ("shoud't print when tween canceled"); //This printed
    }

**Comment by dentedpixel** [comment]
Hi there, that is actually a feature :). You passed true, to the second option in cancel which is callOnComplete, which calls the onComplete method when you cancel. If you do not want this behavior switch that to false.
