### ISSUE TITLE
Orient to path issue

### ISSUE THREAD

**Issue by Rolliboy** [dentedpixel/LeanTween#102]
I noticed a "jump" when orientating a gameObject to path.

The object is following the curve in the right way but some specific handle positions seems to suffer of gimbal or something similar. (maybe is a known issue?)

Thanks

**Comment by dentedpixel** [comment]
Hi there, I am not aware of such an issue. Could you post the path the editor outputs? Also is this for the bezier path or spline? You can adjust the resolution of the spline path which might help, both these variables on LTSpline:

public static int DISTANCE_COUNT = 3; // increase for a more accurate constant speed
public static int SUBLINE_COUNT = 20; // increase for a more accurate smoothing of the curves into lines
