### ISSUE TITLE
tweentype setter not working properly

### ISSUE THREAD

**Issue by jaroslaw-weber** [dentedpixel/LeanTween#103]
i was using tweentype property to set ease, but now it stopped working, need to use ".setEase" instead.
if you are not going to use it in the future please make setter private or fix this.

great plugin btw.

**Comment by jaroslaw-weber** [comment]
i noticed its not setter, its a public field.
you changed onComplete to setOnComplete some time ago, is it something similar?
anyway, leaving it as public field is not good if you cant use it to set tween type.

**Comment by dentedpixel** [comment]
I can see how that's confusing, using the setEase methods is the correct way to set this. 

I have set it to private in the latest commit (also renamed it to easeType as that is a better description)

I am glad you are liking the plugin :)
