### ISSUE TITLE
unique id not really unique?

### ISSUE THREAD

**Issue by jaroslaw-weber** [dentedpixel/LeanTween#104]
my tween was being canceled and i didnt know why because i did not use cancel tween anywhere for that tween. after some checking i found out that i have a method in another class which caches tweens and cancel them by unique id, but it accidentaly cancels the other tween too (in completely different class!).
i see that you are using array index in cancel method, but unique id is misleading in this case. because unique id is not really unique i cant control canceling my tweens....

**Comment by jaroslaw-weber** [comment]
some code
class 1:
`LeanTween.value (ch.gameObject, v=>{....`
class 2:
```
        while(tweensToStop.Count>0)
        {
            var tween=tweensToStop.Dequeue();
            if(tween!=null)
            {
                LeanTween.cancel(tween.uniqueId); //tween from class 1 is cancel but i didnt add it to the queue
            }
        }

```

**Comment by jaroslaw-weber** [comment]
i found closed ticket and stored tweens as int queue instead of LTDescr and it worked.
Although i was little confused. Pooling and reusing tweens?

**Comment by dentedpixel** [comment]
Yup, that is a common mistake :-/ I wish I could make it more explicit that you shouldn't cache off the LTDescr, but instead just use the (int)id to store a reference... I do try to call it out a couple of places in the documentation, but maybe I need to put it more front end center.

**Comment by oleprinds** [comment]
Many people - like myself - will probably learn about the mistake here, when searching for solution.

So as a service and just to be very clear, the correct implementation is like this (example copied from the documentation)

Example:
```
//save the id for later
int id = LeanTween.moveX(gameObject, 1f, 1f).id;

//get the LTDescr back using the id. It will be null if tween was removed
LTDescr d = LeanTween.descr( id );
```
As [jaroslaw-weber](https://github.com/jaroslaw-weber) suggest, the reason for this is that all LTDescr objects up to maxTweens are created in the init function, and LTDescr objects are being reused once a tween is done.
