### ISSUE TITLE
TestingAllCS compile error

### ISSUE THREAD

**Issue by tarchan** [dentedpixel/LeanTween#105]
TestingAllCS compile error on Microsoft Visual Studio 'Attach to Unity'.

CS0121  C# The call is ambiguous between the following methods or properties: and
'LeanTween.value(GameObject, Action<float, float>, float, float, float)' and 'LeanTween.value(GameObject, Action<float, object>, float, float, float)'

**Comment by dentedpixel** [comment]
Hi there, thanks for the heads up, I have pushed what I think should be a fix for the bug, but I don't have the right setup in order to test it. Could you double check it possibly?
