### ISSUE TITLE
No longer runtime allocation free

### ISSUE THREAD

**Issue by 00christian00** [dentedpixel/LeanTween#106]
Hi Ross,
I just noticed the new version of Leantween after the redesign is no longer allocation free at runtime. 
I believe the reason is you are doing things like this : 
this.easeInternal = ()=>{ trans.eulerAngles = easeMethod(); };
What this do is allocate a new delegate every time that contain the above function.
Don't know how to fix it without a major rewrite however as you should declare all delegates and assign them to each tween method.

**Comment by dentedpixel** [comment]
Hmmm I was keeping those functions inline for increased readability. I wonder if I assigned it like:

this.easeInternal = specificMoveMethod;

If that would still have an memory allocation spike?
That would certainly be an easy enough rewrite.

**Comment by 00christian00** [comment]
As long as you declare the delegate in advance outside the method, it should be ok. 
However If you have some methods which use local variables declared outside the delegate you won't have access to them anymore as they won't be visible to it.

**Comment by 00christian00** [comment]
By the way  I wasn't clear.
You cannot do:
this.easeInternal = specificMoveMethod;
The result will be the same.
What you must do is:
Action moveAction = new Action(specificMoveMethod);
and then:
this.easeInternal = moveAction ;

**Comment by dentedpixel** [comment]
Hi Christian,

Although it would seem like Unity would add extra garbage collection for this type of thing I have not seen any evidence of a GC hit for these methods. I have been profiling and do not see any additional garbage collection hits compared when animating 10,000 cubes versus them just sitting still (using LeanTween.move method). Let me know if you can give some examples where you see the extra GC penalty.

Thanks!
