### ISSUE TITLE
setLoopPingPong will cause GC for every frame(unity: 5.5.1, LeanTween 2.44),

### ISSUE THREAD

**Issue by liuxuan123** [dentedpixel/LeanTween#107]
void Start () {
     LeanTween.alpha (imageRectTransform, 0, 0.3f).setLoopPingPong (-1);
} will cause gc for every frame

**Comment by dentedpixel** [comment]
Just curious in how you are measuring the garbage collection? I was able to see an additional garbage collection when looking in the profiler, it was averaging 15 GC Allocations per-frame with no scripts running but then with your script given it was at 16. However once I told the tween not t be recursive it went back to 15... so it might have to do with that. You should be able to add that setting if you want to avoid this extra GC. I will look into see if I can get rid of this extra GC even if it is recursive...

**Comment by dentedpixel** [comment]
I made an update to this method to avoid that one GC per frame. I think I found a good way to test it, so ignore my earlier question.
