### ISSUE TITLE
rotation problem with place on path

### ISSUE THREAD

**Issue by gluckez** [dentedpixel/LeanTween#112]
Hi, 
First of all, great job on the plugin! I prefer it over hotween and itween. But i've been struggeling with a rotation issue for a long time now and can't find any way to fix it. 
I'm using leantween to place an object along the path, but i'd like to rotate it, and have it's forward face the other way. I think i've just about tried anything now, but it allways faces forward towards the last point, never back. can you help me... please? I've been through the documentation, but didn't learn much from that.

P.S.: tried to comment on the dentedpixel website, but wordpress gave me an empty response error. i didn't know where else to go with my problem..

**Comment by dentedpixel** [comment]
Hi there!
Sorry for the late response, unfortunately the best way to do this at the moment is to have the object nested inside of another Transform object, so you can move the child object to whatever rotation you want, but then have the parent following the path.
