### ISSUE TITLE
LeanTween ID reuse bug (complete/cancel/create within same update)

### ISSUE THREAD

**Issue by gnoph** [dentedpixel/LeanTween#114]
Our project makes heavy use of LeanTween to drive a series of animated sequences. We noticed that occasionally certain tweens appeared never executed. Research found that LeanTween might confused two tweens under certain situation because of the incorrect reuse of one of the 400 tween IDs.

To reproduce, create a new MonoBehaviour script and paste in following code. 

```
using System.Collections;
using UnityEngine;

public class LeanTweenIdReuseBug : MonoBehaviour {
	private void Start() {
		// Tween[0] - slot 0 - schedule to complete in 1 second to cancel tween1 and create tween2
		m_Tweens[0] = LeanTween
			.value(gameObject, 0f, 1f, 1f)
			.setOnUpdate((float val) => {
				Debug.Log("tween0: update() val = " + val);
				m_TweenUpdateCalled[0] = true;
			})
			.setOnComplete(() => {
				Debug.Log("tween0: onComplete()");
				m_TweenCompleteCalled[0] = true;
				// Cancel tween1
				Debug.Log("tween0: cancel tween1 with unique id " + m_Tweens[1].id + ", slot # " + (m_Tweens[1].id & 0xFFFF));
				LeanTween.cancel(m_Tweens[1].id);

				// Dummy tween - will reuse slot 0
				LeanTween.value(02, 2f, 2f);

				// Create tween2 - will reuse slot 1
				Debug.Log("tween0: create tween2");
				m_Tweens[2] = LeanTween
					.value(gameObject, 0f, 1f, 1f)
					.setOnUpdate((float val) => {
						Debug.Log("tween2: update() val = " + val + "  //// NEVER HIT");
						m_TweenUpdateCalled[2] = true;
					})
					.setOnComplete(() => {
						Debug.Log("tween2: onComplete()");
						m_TweenCompleteCalled[2] = true;
					});
				Debug.Log("tween2: created with unique id " + m_Tweens[2].id + ", slot # " + (m_Tweens[2].id & 0xFFFF));
			});
		Debug.Log("tween0: created with unique id " + m_Tweens[0].id + ", slot # " + (m_Tweens[0].id & 0xFFFF));

		// Tween1 - slot 1 -  scheduled to complete in 1 second
		m_Tweens[1] = LeanTween
			.value(gameObject, 0f, 1f, 1f)
			.setOnUpdate((float val) => {
				Debug.Log("tween1: update() val = " + val);
				m_TweenUpdateCalled[1] = true;
			})
			.setOnComplete(() => {
				Debug.Log("tween1: onComplete()  //// NEVER HIT");
				m_TweenCompleteCalled[1] = true;
			});
		Debug.Log("tween1: created with unique id " + m_Tweens[1].id + ", slot # " + (m_Tweens[1].id & 0xFFFF));

		StartCoroutine(DelayedReport(1.1f));
	}

	private IEnumerator DelayedReport(float delay) {
		yield return new WaitForSeconds(delay);

		// Print report
		for (int i = 0; i < 3; i++) {
			Debug.Log("Tween[" + i + "] Updated=" + m_TweenUpdateCalled[i] + ", Completed=" + m_TweenCompleteCalled[i]);
		}

		// Turn off futher processing
		gameObject.SetActive(false);
	}

	// Update is called once per frame
	private void Update() {
		Debug.Log("============ TICK ============");
	}

	private readonly LTDescr[] m_Tweens = new LTDescr[3];
	private readonly bool[] m_TweenUpdateCalled = new bool[3];
	private readonly bool[] m_TweenCompleteCalled = new bool[3];
}
```

Expected report output:
> Tween[0] Updated=True, Completed=True
> Tween[1] Updated=True, Completed=False
> Tween[2] Updated=False, Completed=True

Note that tween1's OnComplete() is never called and tween2's OnCompleted() called immediately after creation.

**Comment by gnoph** [comment]
We believe the problem occurred during LeanTween.update().

```
			for( int i = 0; i <= tweenMaxSearch && i < maxTweens; i++){
				tween = tweens[i];
//				if(i==0 && tweens[i].toggle)
//					Debug.Log("tweens["+i+"]"+tweens[i]);
				if(tween.toggle){
					maxTweenReached = i;

					if (tween.updateInternal()) { // returns true if the tween is finished with it's loop
						tweensFinished[finishedCnt] = i;
						finishedCnt++;
					}
				}
			}

			// Debug.Log("maxTweenReached:"+maxTweenReached);
			tweenMaxSearch = maxTweenReached;
			frameRendered = Time.frameCount;

			for(int i = 0; i < finishedCnt; i++){
				j = tweensFinished[i];
				tween = tweens[ j ];
				//				Debug.Log("removing tween:"+tween);
				removeTween(j);
				if(tween.hasExtraOnCompletes && tween.trans!=null)
					tween.callOnCompletes();
			}
```

When first second elapsed, both tween 0 and 1 were included in "tweensFinished" array. In the second loop, the first iteration (i=0) removed tween 0 and called its OnComplete(), which in turns canceled and removed tween 1 and created a dummy tween followed by tween 2. The dummy tween reused the tween 0's ID. Tween 2 reused tween 1's. The second iteration (i=1) removed tween 2 due to reused ID then called tween 2's OnComplete. Both tween 1's OnComplete and tween 2's OnUpdate were lost in the process.

**Comment by dentedpixel** [comment]
Hi there gnoph, thanks for the detailed report. It looks like this has been fixed with a recent similar issue that someone reported. At least it is meeting the expected results when I run it. I change the code slightly to be based off of the ids rather than storing away the LTDescr, but I think it should have the same result:

`private void Start() {
		// Tween[0] - slot 0 - schedule to complete in 1 second to cancel tween1 and create tween2
		m_Tweens[0] = LeanTween
			.value(gameObject, 0f, 1f, 1f)
			.setOnUpdate((float val) => {
				Debug.Log("tween0: update() val = " + val);
				m_TweenUpdateCalled[0] = true;
			})
			.setOnComplete(() => {
				Debug.Log("tween0: onComplete()");
				m_TweenCompleteCalled[0] = true;
				// Cancel tween1
				Debug.Log("tween0: cancel tween1 with unique id " + m_Tweens[1] + ", slot # " + (m_Tweens[1] & 0xFFFF));
				LeanTween.cancel(m_Tweens[1]);

				// Dummy tween - will reuse slot 0
				LeanTween.value(02, 2f, 2f);

				// Create tween2 - will reuse slot 1
				Debug.Log("tween0: create tween2");
				m_Tweens[2] = LeanTween
					.value(gameObject, 0f, 1f, 1f)
					.setOnUpdate((float val) => {
						Debug.Log("tween2: update() val = " + val + "  //// NEVER HIT");
						m_TweenUpdateCalled[2] = true;
					})
					.setOnComplete(() => {
						Debug.Log("tween2: onComplete()");
						m_TweenCompleteCalled[2] = true;
					}).id;
				Debug.Log("tween2: created with unique id " + m_Tweens[2] + ", slot # " + (m_Tweens[2] & 0xFFFF));
			}).id;
		Debug.Log("tween0: created with unique id " + m_Tweens[0] + ", slot # " + (m_Tweens[0] & 0xFFFF));

		// Tween1 - slot 1 -  scheduled to complete in 1 second
		m_Tweens[1] = LeanTween
			.value(gameObject, 0f, 1f, 1f)
			.setOnUpdate((float val) => {
				Debug.Log("tween1: update() val = " + val);
				m_TweenUpdateCalled[1] = true;
			})
			.setOnComplete(() => {
				Debug.Log("tween1: onComplete()  //// NEVER HIT");
				m_TweenCompleteCalled[1] = true;
			}).id;
		Debug.Log("tween1: created with unique id " + m_Tweens[1] + ", slot # " + (m_Tweens[1] & 0xFFFF));

		StartCoroutine(DelayedReport(1.1f));
	}

	private IEnumerator DelayedReport(float delay) {
		yield return new WaitForSeconds(delay);

		// Print report
		for (int i = 0; i < 3; i++) {
			Debug.Log("Tween[" + i + "] Updated=" + m_TweenUpdateCalled[i] + ", Completed=" + m_TweenCompleteCalled[i]);
		}

		// Turn off futher processing
		gameObject.SetActive(false);
	}

	// Update is called once per frame
	private void Update() {
		Debug.Log("============ TICK ============");
	}

	private readonly int[] m_Tweens = new int[3];
	private readonly bool[] m_TweenUpdateCalled = new bool[3];
	private readonly bool[] m_TweenCompleteCalled = new bool[3];`


In case you are curious here is the merge, that I think might have fixed it: https://github.com/dentedpixel/LeanTween/pull/113
