### ISSUE TITLE
leanTween rotation problem

### ISSUE THREAD

**Issue by liuxuan123** [dentedpixel/LeanTween#118]
`RectTransform rect = GetComponent<RectTransform> ();`
`LeanTween.rotate (rect, 360, 3.0f).setRepeat (-1);  `
above code will rotate forever as i want to, but the below code will not work as I use GameObject as 
param to Leantween:
`LeanTween.rotateLocal (rect.gameObject, new Vector3(0, 0, 360), 3.0f).setRepeat (-1);`  
or
`LeanTween.rotateZ(rect.gameObject, 360, 3.0f).setRepeat(-1);`

It seems when pass GameObject to leantween will not rotate more than 180 degree but pass RectTransform will work as expected

**Comment by dvr707** [comment]
I have the same problem too.. 
should this be like this?
`LeanTween.rotate (rect, 360, 3.0f).setLoopPingPong();`

**Comment by dentedpixel** [comment]
I would like to steer you towards using rotateAround and rotateAroundLocal. This will give you the more predictable behavior you want. I have been trying to phase out the standard rotate methods as they have some issues like you have pointed out. This will repeat infinitely:

LeanTween.rotateAroundLocal(gameObject, Vector3.forward, 360f, 1f).setRepeat(-1);

**Comment by seprab** [comment]
> I would like to steer you towards using rotateAround and rotateAroundLocal. This will give you the more predictable behavior you want. I have been trying to phase out the standard rotate methods as they have some issues like you have pointed out. This will repeat infinitely:
> 
> LeanTween.rotateAroundLocal(gameObject, Vector3.forward, 360f, 1f).setRepeat(-1);

It worked. Thanks

**Comment by SwapnilNishad** [comment]
Thank You :)

**Comment by SwapnilNishad** [comment]
> 
> 
> > I would like to steer you towards using rotateAround and rotateAroundLocal. This will give you the more predictable behavior you want. I have been trying to phase out the standard rotate methods as they have some issues like you have pointed out. This will repeat infinitely:
> > LeanTween.rotateAroundLocal(gameObject, Vector3.forward, 360f, 1f).setRepeat(-1);
> 
> It worked. Thanks

Thank You :)

**Comment by soundweaving** [comment]
I found the easiest way to make a 360* rotation via LeanTween. It is pretty easy)

LeanTween.rotateZ(gameObject, 360, 5f).setFrom(0).setRepeat(-1);

The command setFrom(value) actually make all you need, if endless rotation is what you need

**Comment by AlzakiCreativeworks** [comment]
> I found the easiest way to make a 360* rotation via LeanTween. It is pretty easy)
> 
> LeanTween.rotateZ(gameObject, 360, 5f).setFrom(0).setRepeat(-1);
> 
> The command setFrom(value) actually make all you need, if endless rotation is what you need

tried this, but doesn't work on my case.

but this one suggested by dentedpixel works:
LeanTween.rotateAroundLocal(gameObject, Vector3.forward, 360f, 1f).setRepeat(-1);
