### ISSUE TITLE
Cancel Tween by id cause weird flashy behavior

### ISSUE THREAD

**Issue by kevinkassimo** [dentedpixel/LeanTween#119]
Hi, I am developing a game that involves thousands of bullets moving on screen simultaneously, which relies heavily on the recycling of GameObjects (when bullet moves out of the screen field), which I store on some stack. Recycling also requires me to kill all tweens on a GameObject, and I use caching of tween IDs and feed to `LeanTween.cancel(id)`to achieve optimized performance.

And here comes the problem. After a while there will be one or two bullets that completely ignores the tween cancelling and continue moves forward until the tween is finished by itself. In fact, with inspection of frame by frame action, I found that the bullet would ACTUALLY flash back between the two locations: the old location that follows the original tween (which should have been killed) motion path, and the new location that the bullet, when reused, is supposed to be. As I use a stack structure for pooling, the same bullet would immediately be reused after recycled. When some shooter keeps shooting the same type of bullet, what it would result in is that the bullet flashes to the new location with a tween ID, then flashes to the location on the path of the old tween that is supposed to have been killed, then flashes to a newer location with a completely new ID, and stuck in this loop.

What could have been the cause to this problem? Thanks!

**Comment by dentedpixel** [comment]
That all seems like the correct ways to do things. I am not sure what the problem might be. Possibly there just might be a bug in LeanTween... I'll try and add a stress test similar to this one to see if I can recreate.

**Comment by dentedpixel** [comment]
I created a scene to try and test this scenario at LeanTween/Testing/PerformanceTests I couldn't find any bugs with the canceling based on an id, but possibly you can try and modify it to make it more similar to your project and find a bug? Let me know if you are able to do this and I will investigate the problem.
