### ISSUE TITLE
OnComplete called on last update

### ISSUE THREAD

**Issue by dennisfokker** [dentedpixel/LeanTween#120]
As the title suggests: on the very last frame of the animation, before it's rendered by unity, the oncomplete is called.
So, for example, if I would cancel the animation on complete (let's not argue the use of this), and the animation would move the object to x = 0, the gameobject would sit still at around x = 0.0143... (Exact number obviously depending on the animation). In some cases this deviation is very clearly visible.

Myself I simply fixed it by moving the for-loop that calls all onComplete-s before the loop that updates (and marks the animation as finished) the animations, but there might be a more graceful solution (like perhaps an extra "onAfterComplete" event).

**Comment by dentedpixel** [comment]
Is this still a problem? I can't see the issue with the current code, but I believe I may have moved where the for-loops are handled at some point so possibly that is when it was fixed up.
