### ISSUE TITLE
tweenMaxSearch goes out of bounds (by one), crashes tweensRunning and others

### ISSUE THREAD

**Issue by darekrusin** [dentedpixel/LeanTween#123]
I'm using the standard setting of `maxTweens = 400`, lauching and stopping about 350+ tweens (but not going over 400, at least LeanTween is not throwing any errors of that kind). At some point weird thing started happening and I've isolated this simple case below. I've added an extra LogError and it complains that `tweenMaxSearch == 400`, which causes out of bounds array access.

```cs
    public static int tweensRunning{
        get{ 
            int count = 0;

            if (tweenMaxSearch >= tweens.Length)
                Debug.LogError("TWEENS MAX SEARCH TOO LARGE: " + tweenMaxSearch);
            
            for (int i = 0; i <= tweenMaxSearch; i++){
                if (tweens[i].toggle){
                    count++;
                }
            }
            return count;
        }
    }
```

I'm betting the error is caused by this code:

```cs
    public static LTDescr options(){
        init();

        bool found = false;
        //      Debug.Log("Search start");
        for(j=0, i = startSearch; j <= maxTweens; i++){
            if(j >= maxTweens)
                return logError("LeanTween - You have run out of available spaces for tweening. To avoid this error increase the number of spaces to available for tweening when you initialize the LeanTween class ex: LeanTween.init( "+(maxTweens*2)+" );") as LTDescr;
            if(i>=maxTweens)
                i = 0;
            //          Debug.Log("searching i:"+i);
            if(tweens[i].toggle==false){
                if(i+1>tweenMaxSearch)
                    tweenMaxSearch = i+1;
                startSearch = i + 1;
                found = true;
                break;
            }

            j++;
        }
```

That `tweenMaxSearch = i+1;`... if `i` is on the last element of the array, it would cause the tweenMaxSearch to point beyond the array. Note that `startSearch` is set to the same value, but it looks like it will be wrapped to 0 in the future calls to this function. But `tweenMaxSearch` stays out of bounds it will cause problems in other places where it's used.

Am I onto something here? :)

**Comment by dentedpixel** [comment]
I think you are on to something, does replacing this line:
`if(i+1>tweenMaxSearch)
                    tweenMaxSearch = i+1;`
with this:
`if(i+1>tweenMaxSearch && i+1 < maxTweens)
                    tweenMaxSearch = i+1;`
Fix it? I don't have a good recreation setup so I have to rely on your testing any fixes :-/

**Comment by darekrusin** [comment]
I did the test and:

* Before the change: 4 out of 4 tests fail.
* After the change: 4 out of 4 tests work properly.

So it looks like it does fix my test case. I can't speak about the specifics of the fix itself because I don't have enough understanding of LeanTween code. I bet you know what you're doing there though :)

Thanks for creating LeanTween, by the way. Very useful tool!

**Comment by dentedpixel** [comment]
Oh great! It looks to be a safe change in the tool overall (shouldn't effect other people's work).
