### ISSUE TITLE
Feature Request: Update LeanTween functions to be Extension methods

### ISSUE THREAD

**Issue by quinnhoener** [dentedpixel/LeanTween#127]
Could we update functions to be Extension methods for ease of use? Instead of doing:

```
LeanTween.moveX(gameObject, 1, 1);
```
This could be 
```
gameObject.moveX(1, 1);
```

All this would take is adding the "this" keyword to the first parameter.

```
public static LTDescr moveX(this GameObject gameObject, float to, float time){
// stuff
}
```

**Comment by dentedpixel** [comment]
That's a good idea! I am looking into it now... I think in order to make sure it doesn't conflict with anyone else's extensions I will have the methods with this signature:

LeanMoveX (instead of just moveX)

**Comment by dentedpixel** [comment]
I have added a first pass of most of the methods. Please take a look and let me know if you see any issues!
