### ISSUE TITLE
Alpha on children

### ISSUE THREAD

**Issue by adamhbz** [dentedpixel/LeanTween#130]
Hi, I have a gameobject that has a sprite component on the root gameobject. It also has additional sprites as children of the game object.

I would like to fade in the alpha of the root gameobject and then fade in the children at a later time. Currently, it seems to fade in all of the children with the root game object. Is there a way to add a flag so it ignores the children?

-- GameObject (with SpriteRenderer)
| -- Child GameObject (with SpriteRenderer)
| -- Child GameObject (with SpriteRenderer)

All fade in together but I would like only the top level to fade in.

Thanks, adam.

**Comment by dentedpixel** [comment]
Sorry for the slow reply! You need to set setRecursive( false), like:

LeanTween.alpha( rootGameObject, 0f, 1f).setRecursive( false );

**Comment by steelei** [comment]
alphaRecursiveSprite() does not check the value of useRecursion -- setRecursive(false) does nothing to prevent the alpha of child SpriteRenderers from changing.
