### ISSUE TITLE
Example code errors

### ISSUE THREAD

**Issue by AsLogd** [dentedpixel/LeanTween#27]
Hi, I was taking a look at this plugin but I couldn't give it a try. The example codes give me a bunch of errors, all of the same style:

Assets/LeanTween/LeanTweenExamples/Scripts/EventListenersScatteredJS.js(30,20): BCE0018: The name 'LTEvent' does not denote a valid type ('not found'). 

Google says it's related to a missing import or something with the compilation order of standard folders. But I don't really know what's going on.

Any idea?

Thanks

**Comment by ArdentKid** [comment]
Hi dentedpixel,

How can i make Monodevelop recognize the plugin?

**Comment by dentedpixel** [comment]
Hi Omid,
I am not sure what you mean. Are you getting errors in Monodevelop? I
actually don't use it much since I find it a little clunky (I prefer
Sublime Editor), but let me know how I can help.

Thanks,
Russ

On Tue, Mar 10, 2015 at 3:42 AM, Omid Ahourai <notifications@github.com>
wrote:

> Hi dentedpixel,
>
> How can i make Monodevelop recognize the plugin?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dentedpixel/LeanTween/issues/27#issuecomment-78008115>
> .
>



-- 
Twitter - http://twitter.com/DentedPixel
Facebook - http://www.facebook.com/DentedPixel
Website - http://dentedpixel.com

**Comment by ArdentKid** [comment]
Sorry for the late reply. Not sure what fixed the issue, but yes monodevelop just wasn't recognizing the plugin before. Works now.

**Comment by dentedpixel** [comment]
Great! Someone mentioned it doesn't work in Monodevelop 3.5. So make sure
to use 4.0 and above (maybe using a greater version is what fixed it).

On Mon, Mar 30, 2015 at 3:15 AM, Omid Ahourai <notifications@github.com>
wrote:

> Sorry for the late reply. Not sure what fixed the issue, but yes
> monodevelop just wasn't recognizing the plugin before. Works now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dentedpixel/LeanTween/issues/27#issuecomment-87576617>
> .
>



-- 
Twitter - http://twitter.com/DentedPixel
Facebook - http://www.facebook.com/DentedPixel
Website - http://dentedpixel.com
