### ISSUE TITLE
LeanTween.value with float always tweening towards zero.

### ISSUE THREAD

**Issue by Murcho** [dentedpixel/LeanTween#35]
Running in Unity 5 beta 14.  Using the latest version of LeanTween from the Unity Asset Store (2.19)

If the setOnUpdate method is used, the output value always tweens from the "from" value to zero, and ignores the "to" value.  If the method is passed in the original call to LeanTween.value() it works correctly.

The same results occurred when using Vector3 values instead of floats as well.

E.g.

This code works correctly (m_EditPanel is a RectTransform)

```
LeanTween.value(m_EditPanel.gameObject, (float pos) =>
    {
        Debug.Log("On Update Off : " + pos);
        var min = m_EditPanel.anchorMin;
        min.x = pos;
        m_EditPanel.anchorMin = min;
        var max = m_EditPanel.anchorMax;
        max.x = pos + 0.658f;
        m_EditPanel.anchorMax = max;
    }, 0.342f, 1f, 0.5f).setEase(LeanTweenType.easeOutSine);
```

And this is the code that tweens towards zero.

```
LeanTween.value(m_EditPanel.gameObject, 0.342f, 1f, 0.5f).setEase(LeanTweenType.easeOutSine).setOnUpdate((float pos) =>
    {
        Debug.Log("On Update Off : " + pos);
        var min = m_EditPanel.anchorMin;
        min.x = pos;
        m_EditPanel.anchorMin = min;
        var max = m_EditPanel.anchorMax;
        max.x = pos + 0.658f;
        m_EditPanel.anchorMax = max;
    });
```

**Comment by miki-regresa** [comment]
omg, how are you so cool, thank you very much holy molly!!!
