### ISSUE TITLE
Cannot implicitly convert type `UnityEngine.Mesh' to `Mesh'

### ISSUE THREAD

**Issue by anagashi123** [dentedpixel/LeanTween#37]
When I imported some works from my friend, and it gave me this error. 

![leantween_error](https://cloud.githubusercontent.com/assets/10512352/5717834/a9a09e22-9b41-11e4-84b7-e916588c7f6d.png)

Please help me solve this problem, thank you.

**Comment by dentedpixel** [comment]
Hmmm, I have no idea why that would just start showing up. I would just comment out those lines that are mentioned. It is associated with the alphaVertex action that most people do not use anyway...
