### ISSUE TITLE
Color Tween for SpriteRenderer

### ISSUE THREAD

**Issue by eatcodeplay** [dentedpixel/LeanTween#39]
I've noticed that Leantween is missing color tweens for spriterenderers

so just add this at Line 2234 :)

```
var sprRen = trans.gameObject.GetComponent<SpriteRenderer>();
if (sprRen != null) {
    sprRen.color = toColor;
}
```

Cheers and thanks for this great tween library! :)

**Comment by dentedpixel** [comment]
Oh thanks! I love it when the opened issue even contains exact instructions in how to fix it :)

I am glad you are enjoying LeanTween. I will include this in the next update.

**Comment by LevelZed** [comment]
And for those who want to change from any color (not only from white) also replace the code at Line 1250 between #else & #endif with:
```
					SpriteRenderer renColor = trans.gameObject.GetComponent<SpriteRenderer>();
					if(renColor!=null){
						Color col = renColor.color;
						this.setFromColor( col );
					}else{
						if(trans.gameObject.renderer!=null && trans.gameObject.renderer.material.HasProperty("_Color")){
							Color col = trans.gameObject.renderer.material.color;
							this.setFromColor( col );
						}else if(trans.gameObject.renderer!=null && trans.gameObject.renderer.material.HasProperty("_TintColor")){
							Color col = trans.gameObject.renderer.material.GetColor ("_TintColor");
							this.setFromColor( col );
						}else if(trans.childCount>0){
							foreach (Transform child in trans) {
								if(child.gameObject.renderer!=null){
									Color col = child.gameObject.renderer.material.color;
									this.setFromColor( col );
									break;
		    					}
							}
						}
					}
```

**Comment by dentedpixel** [comment]
Great! Thank you LevelZed for the suggestion. I have added this code change in to the latest commit to github. Please let me know if there are any issues with it.

**Comment by LevelZed** [comment]
Hey bro, i've just upgraded to Unity 5 and updated your lib (2.27) from the AssetStore.
Looks like you forgot to add the eatcodeplay's comment (the 1st on this page) to LeanTween.cs line #2 194. But did not forget to add mine :)
So changing sprite color doesn't work or works weird in the 2.27 version (creates a material instance).

You rock, i love your lib!!! :)

**Comment by dentedpixel** [comment]
Woops! Thanks for the heads up LevelZed.  I think I got it right this time. If you want to take a look at the latest commit, I have attempted to make the color tweening on a sprite not act wonky.

Thanks for your support :), I am glad it has been working well for you!
