### ISSUE TITLE
[Suggestion] useEstimatedTime 

### ISSUE THREAD

**Issue by vicenterusso** [dentedpixel/LeanTween#40]
Just wondering if the line [2130](https://github.com/dentedpixel/LeanTween/blob/master/Assets/Plugins/LeanTween.cs#L2130) could be changed to
```
dtEstimated = Time.unscaledDeltaTime;
```
Also, remove the "0.2f" adjustment.

**Comment by dentedpixel** [comment]
Thanks Vicent! I have been meaning to add this in, but sometimes I need some reminding :)

I think this only became available in the 4.x version of Unity. I am not sure exactly what version but I think it is pretty safe to only include it in 4.3 and later, I will keep my old code as a fallback for earlier versions (I still support 3.5, although I am not sure if anyone actually uses this anymore).

**Comment by dentedpixel** [comment]
Nevermind it looks like 4.3 didn't have it yet. I will just have it be 4.6 and up which works.

**Comment by vicenterusso** [comment]
It was introduced on 4.5
