### ISSUE TITLE
Request to Break out LeanAudio and LeanTest into their own files

### ISSUE THREAD

**Issue by bncastle** [dentedpixel/LeanTween#43]
I would like to put LeanAudio and LeanTest into their own files separate from LeanTween. This would allow only including the pieces needed for a particular project. It would also make the code easier to navigate as LeanTween.cs is at this point pretty big.

**Comment by dentedpixel** [comment]
That's a good idea, I have been toying with the idea myself for awhile, I just didn't want to confuse anyone who isn't actually digging into the internals. LeanAudio and LeanTest are in working order but aren't really as feature rich as I have envisioned them, but I guess you have to launch at some point.
