### ISSUE TITLE
 not call oncomplete on start

### ISSUE THREAD

**Issue by emperor1412** [dentedpixel/LeanTween#44]
Hi, it seems that the latest version 2.25 and even earlier version 2.24 has the bug that does not call oncomplete on start

when I use like this for example :

Code (CSharp):
LeanTween.moveLocalX(gameObject, 5, 5).setOnComplete(Complete).setOnCompleteOnStart(true);
 
or
 
LeanTween.moveLocalX(gameObject, 5, 5).setOnComplete( () => {
            Debug.Log("on complete move local X");
        }).setOnCompleteOnStart(true);

**Comment by dentedpixel** [comment]
Thanks for pointing this out, I had only implemented it for the callback tween type. It should work for all tween types now, if you want to check out the latest version committed.

**Comment by danieldownes** [comment]
I'm using it on LeanTween.scale, and setOnStart is called immediately, disregarding setDelay.
