### ISSUE TITLE
Library in DLL

### ISSUE THREAD

**Issue by jjhesk** [dentedpixel/LeanTween#47]
Since I have no idea how to produce the dll files in monodeveloper and use it as the library for other projects. Are there any chances that you will able to compile a dll file for us to use in handy?

**Comment by dentedpixel** [comment]
I actually had never done this either, here is a handy guide to creating DLLs http://docs.unity3d.com/Manual/UsingDLL.html and this is also helpful http://forum.unity3d.com/threads/reducing-script-compile-time-or-a-better-workflow-to-reduce-excessive-recompiling.148078/#post-1026639 .

I went ahead and made a DLL for LeanTween, it is in the Plugins directory zipped up (LeanTween.dll.zip)
