### ISSUE TITLE
Sphere Routing

### ISSUE THREAD

**Issue by jjhesk** [dentedpixel/LeanTween#48]
What is the tween to work on the sphere when there is a position on the sphere surface, let say point A, to another sphere surface point B. What is the quick easy way to get the tween easing done?

**Comment by dentedpixel** [comment]
If you can get the position on both of the Spheres that you can just use the LeanTween.move method to move from one to another.  I think your biggest difficulty will be getting those positions though, that type of 3d math can be tricky and I would need the exact scenario to figure out what you want to achieve.

**Comment by jjhesk** [comment]
i have an radius R, from the surface point A, go to Point B. I would like the object to be rotated along the path so that it will looked like its been running on the sphere surface. The distance has been taken 15 degree.

**Comment by dentedpixel** [comment]
You could use LeanTween.rotateAround ( gameObject, Vector3.left, 90f, 1f );  The hard part will be finding the axis to rotate around... 

I think through some combination of Unity's lookat function ( http://docs.unity3d.com/ScriptReference/Transform.LookAt.html ) and using rotateAround you could get it work...
