### ISSUE TITLE
OnUpdate still being called after pause

### ISSUE THREAD

**Issue by n0wak** [dentedpixel/LeanTween#51]
If I use setOnUpdate on a Tween and later pause the tween, whatever I specified in setOnUpdate still gets called (sending the same value). Perhaps this is intended but this seems weird to me. Shouldn't setOnUpdate be called only if there's an actual update and the tween is active? It's easy to work around but

**Comment by dentedpixel** [comment]
Yeah this does sound like a bug, I hadn't thought of that scenario before. I fixed it in the latest commit, let me know if you see any more issues :)
