### ISSUE TITLE
Can't cancel a tween by id

### ISSUE THREAD

**Issue by zeroc** [dentedpixel/LeanTween#7]
Hello,

First of all, great plugin! I'm using it intensively in our game.
It seems the removeTween function can't process the new backId.
Could you take a look?

Thank you

**Comment by dimmduh** [comment]
I also got into this hole (
I think it's not expected behaviour when "pointer" (LTDescr) updates, but it depends of programming background.

**Comment by iletai** [comment]
hi @dentedpixel 
I tried your solution,  `OnDisable()` and I received Error: `IndexOutOfRangeException: Index was outside the bounds of the array ID.```

So can I use way as an alternative method???

```
        private LTSeq seqSample;
        //Dosomething with Tween
        public  void DoSomething();
        private void OnDisable()
        {
           //Triggerpoint I want cancel:
            seqSample = null;
        }
```
