### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by phest** [dentedpixel/LeanTween#71]
Great library, thanks for sharing.

I'm thinking about adding it to my project, but I noticed you didn't include a license yet. Having no license means that - legally - your code can't be reproduced or derived, not sure if that's what you intended. [1] For a quick fix I would suggest simply pasting something like

> This project is licensed under the terms of the MIT license.

at the end of the readme, or including a license file. Most repos on github use the MIT license because it's permissive, allowing code to be used in proprietary projects while retaining the original copyright. [2]

[1] https://help.github.com/articles/open-source-licensing
[2] https://github.com/blog/1964-open-source-license-usage-on-github-com

**Comment by dentedpixel** [comment]
Oh I guess my phrasing of the license I am using was somewhat incomplete, I copied all of the legalese of the MIT license into the top of the LeanTween.cs class, but I never explicitly said, this the MIT license. I'll have to correct that! I pushed updated wording to the master branch.

Thanks for letting me know, and I am glad you are liking the library :)

**Comment by phest** [comment]
Apologies, I missed the license in LeanTween.cs, I should have looked deeper. Thanks for making it more explicit.
