### ISSUE TITLE
SceneManager.onSceneLoaded does not exist in Unity5.3

### ISSUE THREAD

**Issue by bncastle** [dentedpixel/LeanTween#75]
The bit of code below found in LeanTween.cs (line 1382) produces a compile error in Unity **5.3** because the field being referenced does not exist. Looks like it was added in 5.4 not 5.3. Actually the **5.4b** documentation on Unity's site shows the event as being SceneManager.sceneLoaded.

```c#
#if UNITY_5_3_OR_NEWER
	SceneManager.onSceneLoaded += internalOnLevelWasLoaded;
#endif
```

**Comment by dentedpixel** [comment]
Oh weird, thanks for letting me know! I wasn't getting that error on my Unity 5.3, but maybe I have a slightly later subversion of it (5.3.2). Anyways, I changed it to 5_4_OR_NEWER just to be safe :)
