### ISSUE TITLE
alpha tweens material TintColor instead of SpriteRenderer color property on 2d sprite objects

### ISSUE THREAD

**Issue by sebtoun** [dentedpixel/LeanTween#76]
When the SpriteRenderer is in a child of the tweened GameObject, the material property Tint is tweened instead of SpriteRenderer color. It seems that the recursion only account for TintColor and Color material properties and that the SpriteRenderer is only searched for in the root gameObject.

**Comment by dentedpixel** [comment]
I fixed it up so that recursive color tweening should work for SpriteRender as well.
