### ISSUE TITLE
DLL is outdated

### ISSUE THREAD

**Issue by floutre** [dentedpixel/LeanTween#79]
Hello!

I updated leantween to latest through Unity's Asset Store. I needed alphaCanvas, so I was quite happy.
No problem if I use LeanTween scripts, but for many reason (including compile time), I would rather use the DLL. Except the DLL is outdated, and alphaCanvas does not exist in it.

Could you please update the DLL and push it on the store again? Or maybe put up a small tutorial on how to make the DLL ourselves from the script files in the package?

Thanks

**Comment by dentedpixel** [comment]
You are right, it is slightly out of date, I didn't think anyone would notice :), but that is a pretty key feature. I will recompile a new DLL in the next day or two (it's kind of hard to do unfortunately, so I can't easily supply instructions)

**Comment by dentedpixel** [comment]
I have updated the zipped up DLL with the latest. I also plan on updating the Asset Store LeanTween soon (maybe this weekend). So once I do it will be available there too (although approval can take over a week, so best to get it on github first).
