### ISSUE TITLE
Give an additional custom parameter to a LeanTween

### ISSUE THREAD

**Issue by BenoitFreslon** [dentedpixel/LeanTween#8]
Hello,

Is it possible to add a custom parameter in a LeanTween.delayedCall?Like this:
`
GameObject go;
LeanTween.delayedCall (gameObject, 1f, myFunction, go);
`
Thanks.

**Comment by EagleSigma** [comment]
Saved me tons of time. Thanks BenoitFreslon!

**Comment by samana1407** [comment]
Thanks you, BenoitFreslon!
