### ISSUE TITLE
Color tweening allocate memory at runtime

### ISSUE THREAD

**Issue by 00christian00** [dentedpixel/LeanTween#81]
Hi,
I noticed you now use the GetComponent inside the update method when doing a color tween.
I don't think  it was there before. The getcomponent it's slow and allocate memory so it shouldn't be there, it should be cached at tween start. I am talking of this code at line 655:
`#if !UNITY_3_5 && !UNITY_4_0 && !UNITY_4_0_1 && !UNITY_4_1 && !UNITY_4_2
							SpriteRenderer ren = trans.gameObject.GetComponent<SpriteRenderer>();
							if(ren!=null){
								ren.color = toColor;
								colorRecursiveSprite( trans, toColor);
							}else
#endif`

Also the conditional compilation is wrong as it include one extra bracket.

**Comment by 00christian00** [comment]
Ok, I just read the allocation is only in the editor and not on the build.
Still checking for the component every time is expensive.

**Comment by dentedpixel** [comment]
You are right, I put that in as a temporary hack when the SpriteRenderer came out, and never got around to optimizing it. It should be fixed now.
