### ISSUE TITLE
LeanTween.reset() NPE

### ISSUE THREAD

**Issue by Mazyod** [dentedpixel/LeanTween#83]
Hello, and thanks for this great library!

Following your suggestion in #80, I've added unconditional `LeanTween.reset()` at the start of each scene, but now facing some NullPointerExceptions:

```csharp
public static void reset(){
	for (int i = 0; i <= tweenMaxSearch; i++){
        tweens[i].toggle = false; // This line
    }
	tweens = null;
	Destroy(_tweenEmpty);
}
```

I think there should either be a check in the beginning of the function to make sure a reset is necessary. Personally, I would simply never make `tweens` null, and set it to empty array/list instead.

Best,

**Comment by dentedpixel** [comment]
Good Catch!
I added a null check for this scenario if you want to pull the latest.
