### ISSUE TITLE
Is there a way to save all running tweens?

### ISSUE THREAD

**Issue by matej-zajacik** [dentedpixel/LeanTween#85]
For games that have a full-state save system, where basically everything non-static is saved on user request, is there a way to also save all currently running tweens? Is this built into the lib or something we would need to implement ourselves? (We already have a full-state save system.)

Thank you!

**Comment by dentedpixel** [comment]
Hey there,
Yeah unfortunately this is not built into the library, I never thought of it as a use case :-/

**Comment by dentedpixel** [comment]
Oof yeah that sounds like a huge task. When I usually do state saving, it's just saving to the last check-point, and not saving that precise time. So that makes it a little easier and does not require saving a tween in a halfway done state.
