### ISSUE TITLE
Punch scale seems broken

### ISSUE THREAD

**Issue by virtualboys** [dentedpixel/LeanTween#86]
When using the scale function and punch ease type, different axes will scale at different rates. Sometimes z scale will be very exaggerated, sometimes x etc. I even tried calling the different axes separately: 

```
LeanTween.scaleX (bump, (bump.transform.localScale * 1.5f).x, 15f).setEase (LeanTweenType.punch);
LeanTween.scaleY (bump, (bump.transform.localScale * 1.5f).y, 15f).setEase (LeanTweenType.punch);
LeanTween.scaleZ (bump, (bump.transform.localScale * 1.5f).z, 15f).setEase (LeanTweenType.punch);
```

**Comment by dentedpixel** [comment]
Hi there, I was attempting to recreate your issue at LeanTween/Testing/TestingIssue scene but I can not see the problem you are describing. Are you able to see the issue on this scene?

**Comment by virtualboys** [comment]
Yes I am. It seems to be related to applying multiple tweens to the same object over and over

**Comment by dentedpixel** [comment]
Ok. You should make sure to cancel a previous tween before starting a new one, like: LeanTween.cancel( bump );

or check if it has a current animation with LeanTween.isTweening( bump )
