### ISSUE TITLE
Is there a way to instruct an active tween to jump immediately to the final state?

### ISSUE THREAD

**Issue by gfaraj** [dentedpixel/LeanTween#87]
Often in games, there's a "touch to skip" feature for animations that might get in the way of players. Is there a way to tell all tweens to jump immediately to the destination when the player elects to skip?

**Comment by dentedpixel** [comment]
Yes, you can changed the passed value of LTDescr to be the same as the time the tween is expected to take, for example:

int id = LeanTween.moveX( gameObject, 100f, 10f ).id;

// Skip to the end
LTDescr d = LeanTween.descr( id );
d.passed = 10f;//

**Comment by K0ST4S** [comment]
My project is tweening multiple things at once, and it's hard to keep track of all intervals. I missed some more normalized solution.

**Comment by Saito197** [comment]
> My project is tweening multiple things at once, and it's hard to keep track of all intervals. I missed some more normalized solution.

Instead of saving the Tween id(s) as variable(s) this worked for me: 

```
var tweens = LeanTween.descriptions(gameObject);
foreach (var tween in tweens)
{
    tween.setPassed(tween.time);
}
```
