### ISSUE TITLE
Reloading scene, tweens not working

### ISSUE THREAD

**Issue by cedtat** [dentedpixel/LeanTween#88]
Hello,

I have a strange behavior. When I reload my scene, tweens are not playing (probably because a reference is kept somewhere in the ~LeanTween object)

Do I need to reset tweens ? How can I do that ?

Thank you,
Cédric

**Comment by dentedpixel** [comment]
Hi Cedric,
Sorry for the late response! You can call LeanTween.reset(); to reset the system. LeanTween should work fine between scenes, but you might have uncovered a bug. If you can provide any more steps, to how the bug shows up that would be great. I have recently fixed a bug on the github version regarding scene switching if you want to check out the latest.

**Comment by praschl** [comment]
I hav turned off "Reload Domain" in "Project Settings"->"Editor", which caused that bug for me, too. Tweens were working only the first time after scripts were recompiled, but not any time after.

I added `LeanTween.reset()` into the Awake() of my SceneManager, which fixed it.

**Comment by irtezamasud-blendbrain** [comment]
I found the issue why it wasn't working in most of the cases. (Leantween.reset, cancelall; nothing worked for me).  While I reloaded back to my previous scene Somehow Time.timescale set to 0 (I didn't do a single thing); I figured it out from project settings> Time. That's why tween isn't playing.

I faced this "Time" issue several times with unity while I hadn't done nothing.(Maybe a bug).
Setting time.timescale to 1 at the start or awake will fix the issue and tween will work perfectly.

**Comment by nevyn** [comment]
I just aded LeanTween to my project and got this bug. `LeanTween.reset();` in `Awake()` worked around it for me, but clearly some LeanTween state isn't properly reset between editor invocations.

Here's the only other LeanTween code in my project, if that helps narrow it down. It's applied to a TextMeshPro label.

```csharp
    public void onCombo(string combo)
    {
        comboLabel.text = combo;

        // only show combo label when you've done a few in a row
        if(int.Parse(combo) < 1)
            return;
         
        comboLabel.gameObject.SetActive(true);
        comboStaticLabel.gameObject.SetActive(true);
        LeanTween.cancel(comboLabel.gameObject);
        comboLabel.transform.localScale = new Vector3(0.02f, 0.02f, 0.02f);
        comboLabel.transform.LeanScale(new Vector3(0.01f, 0.01f, 0.01f), 0.3f).setEaseOutQuad();
    }
```
