### ISSUE TITLE
LeanTween.Value(GameObject,Actions,Vector3,Vector3,time) seem to be not work at 2.4.0

### ISSUE THREAD

**Issue by giangqaz** [dentedpixel/LeanTween#89]
I create a new tween by 
 ```
LeanTween.value(gameObject, (value) =>
        {
            Debug.Log(value);
        }, Vector3.one, Vector3.zero, 3f);
```
But the value is always Vector3.zero.
It is ok with 
` LeanTween.value(gameObject, (value) =>
        {
            Debug.Log(value);
        }, 1, 0, 3f)`

**Comment by dentedpixel** [comment]
Thanks Giangqaz for bringing this to my attention. I have fixed it on the latest github version (I will probably submitted an updated version to the asset store soon as well). Let me know if you continue to see any issues.
